# Site settings
title: Remote Work The Right Way
email: your-email@domain.com
description: Have you ever head about “Remote work”? There are a lot of resources regarding this topic analyzing it from several perspectives.
  We want to sum up the best of those to let you know if this way of work is “right” for you and how make it works at the best!
baseurl: "" # the subpath of your site, e.g. /blog
url: "remoteworktherightway.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
