# Site settings
title: Remote Work The Right Way
description: Have you ever head about “Remote work”? There are a lot of resources regarding this topic analyzing it from several perspectives.
  We want to sum up the best of those to let you know if this way of work is “right” for you and how make it works at the best!
baseurl: ""
url: "remoteworktherightway.com"

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM

defaults:
    -
      scope:
          path: ""
      values:
          sitemap: false

exclude: ['CNAME', 'LICENSE', 'README.md']
